language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - hhvm
  
env:
  global:
    - PLUGIN_NAME=Serializable
    - PLUGIN_PATH=Plugin/Serializable
    - REQUIRE="imsamurai/cakephp-environment:dev-master phpdocumentor/phpdocumentor:2.*"
    - DB=mysql
    - CAKE_VERSION=2.5
    - secure: ihPDL7+e2IKrCHOSHWtbct4Bj17lCgzL99p9wG9heoJ44tUvt4/V38/0gnkIc/W5cdZBStJ/1L9oqf1uvl1j7kRQw+kbmTCkRHc7lqwadtc6g4wSzS25Uv7QwF85h5QsA/wJwbBywJdK1FvJawC7iWT/WmgfxOcz+K55Iy3GbHY=
  matrix:
    - CAKE_VERSION=2.3
    - CAKE_VERSION=2.4
    - CAKE_VERSION=2.5

matrix:
  include:
    - php: 5.5
      env:
        - COVERALLS=1
    - php: 5.5
      env:
        - PHPCS=1
    - php: 5.5
      env:
        - FOC_VALIDATE=1
    - php: 5.5
      env:
        - PHPDOC=1
        
before_script:
  - git clone git://github.com/imsamurai/travis-plugin-build.git --depth 1 travis
  - chmod +x ./travis/*
  - ./travis/before_script.sh

script:
  - ./travis/script.sh

after_success:
  - ./travis/after_success.sh

notifications:
  email: im.samuray@gmail.com